fos_rest:
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  body_listener: true
  view:
    formats: {json: true, xml: false, rss: false}
    view_response_listener: force
  serializer:
    serialize_null: true
  # format_listener:
  #   rules:
  #     - { path: '^/api/', priorities: ['json'], fallback_format: 'json' }